### ISSUE TITLE
[Bug] stepper_z1 direction in config not working properly on TMC2208

### ISSUE THREAD

**Issue by jasonhamilton** [Klipper3d/klipper#4882]
This machine is a cartesian setup with two steppers on the z axis running TMC2208 drivers in UART mode.  In the [stepper_x] config section (and with all other axis) I'm able to preface the dir_pin value with "!" in order to get the direction to reverse, however adding the "!" in the [stepper_z1] section does not change the direction.

I rewired my stepper but wanted to report it so it can be looked into.  I don't have a dump since there was not an error but I'll include my config file below in case I've misconfigured something.  I'm running the firmware on a BTT Octopus. 

```yaml
[printer]
kinematics: cartesian
max_velocity: 300
#max_accel: 900 
max_accel: 7000
max_accel_to_decel: 7000
max_z_velocity: 5
max_z_accel: 100

[force_move]
enable_force_move: True


[firmware_retraction]
retract_length: 1
retract_speed: 40
unretract_speed: 40
#unretract_extra_length: 0


[mcu]
serial: /dev/serial/by-id/usb-Klipper_stm32f446xx_29003D000750534E4E313020-if00

[mcu nano]
# For PT100 sensor
serial: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
pin_map: arduino

# [mcu rpi]
# serial: /tmp/klipper_host_mcu


#####################################################################
# 	                X/Y/Z Stepper Settings
#####################################################################

## X Stepper on MOTOR0
[stepper_x]
step_pin: PF13
dir_pin: !PF12
enable_pin: !PF14
rotation_distance: 40
microsteps: 16
endstop_pin: !PG6
position_endstop: -9
position_min: -9
position_max: 200
homing_speed: 25 
#homing_retract_dist: 5

[tmc2209 stepper_x]
uart_pin: PC4
run_current: 1.2
hold_current: 0.520
stealthchop_threshold: 99999


## Y Stepper on MOTOR1
[stepper_y]
step_pin: PG0
dir_pin: !PG1
enable_pin: !PF15
rotation_distance: 40
microsteps: 16
endstop_pin: !PG9
position_endstop: -2
position_min: -2
position_max: 200
homing_speed: 25
# homing_retract_dist: 5

[tmc2209 stepper_y]
uart_pin: PD11
run_current: 1.2
hold_current: 0.520
stealthchop_threshold: 99999


## Z0 Stepper - MOTOR2_1
[stepper_z]
step_pin: PF11
dir_pin: !PG3
enable_pin: !PG5
rotation_distance: 8
microsteps: 16
endstop_pin: !PG10
position_endstop: 0
position_min: 0
position_max: 200
homing_retract_dist: 5

[tmc2209 stepper_z]
uart_pin: PC6
run_current: 1.5
hold_current: 0.520
stealthchop_threshold: 99999


##	Z1 Stepper - MOTOR2_2
[stepper_z1]
step_pin: PG4
dir_pin: !PC1
enable_pin: !PA0
rotation_distance: 8
microsteps: 16

[tmc2209 stepper_z1]
uart_pin: PC7
run_current: 1.5
hold_current: 0.520
stealthchop_threshold: 99999




#####################################################################
# 	Extruder
#####################################################################

#	E0 on MOTOR5
[extruder]
step_pin: PC13
dir_pin: PF0
enable_pin: !PF1
rotation_distance: 22.6789511
gear_ratio: 50:17				#BMG Gear Ratio
microsteps: 16
full_steps_per_rotation: 200	#200 for 1.8 degree, 400 for 0.9 degree
nozzle_diameter: 0.400
filament_diameter: 1.75
heater_pin: PA2
##	Validate the following thermistor type to make sure it is correct
sensor_type: PT100 INA826
# sensor_pin: PF3
sensor_pin: nano:analog1
min_temp: 10
max_temp: 400  
max_power: 1.0
# min_extrude_temp: 170
min_extrude_temp: 20

control: pid
pid_Kp: 27.350
pid_Ki: 1.919
pid_Kd: 97.465

# Extruder at 260 with heater and bed
# pid_Kp: 27.350
# pid_Ki: 1.919
# pid_Kd: 97.465

## Extruder @ 220
#pid_Kp: 25.432
#pid_Ki: 1.842
#pid_Kd: 87.770

pressure_advance: 0.4
# PLA = 0.5
# ESun ABS = 0.4


# pressure_advance_smooth_time: 0.040
# pressure_advance_lookahead_time: 0.05


[tmc2209 extruder]
uart_pin: PE4
interpolate: false
run_current: 1.6
hold_current: 1.4
# sense_resistor: 0.110
stealthchop_threshold: 0


#####################################################################
# 	Bed Heater
#####################################################################

[heater_bed]
##	SSR Pin - BED_OUT
heater_pin: PA8
sensor_type: NTC 100K beta 3950
sensor_pin: PF3
# max_power: 0.6
min_temp: 0
max_temp: 160
control: pid
pid_Kp: 49.403
pid_Ki: 1.672
pid_Kd: 364.963

## Bed @ 60
# pid_Kp: 49.403
# pid_Ki: 1.672
# pid_Kd: 364.963

#####################################################################
# 	                    HEATED CHAMBER
#####################################################################


[heater_generic chamber]
gcode_id: T3
heater_pin: PA3
max_power: 1.0
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PF4
pwm_cycle_time:0.300
#smooth_time:
control: pid
pid_Kp: 24.291
pid_Ki: 0.768
pid_Kd: 192.206

## Chamber @ 60 with bed on
# pid_Kp: 24.291
# pid_Ki: 0.768
# pid_Kd: 192.206

## Chamber @ 50
# pid_Kp: 49.403
# pid_Ki: 1.672
# pid_Kd: 364.963

#pwm_cycle_time:
min_temp: 10
max_temp: 145


[heater_fan chamber_heater_fan]
pin: PD15
heater: chamber
#idle_timeout: 30


#####################################################################
# 	Fan Control
#####################################################################

[heater_fan hotend_fan]
pin: PD12
heater: extruder
heater_temp: 100.0

# Part Cooling Fan
[fan]
pin: PD13

#####################################################################
# 	Coolant Pump Control
#####################################################################

[temperature_fan extruder_stepper]
# actives the coolant pump based on external temperature of the extruder stepper motors
pin: PE5
min_temp:0
max_temp: 80
target_temp: 40
sensor_pin: PF6
sensor_type: EPCOS 100K B57560G104F
control: watermark
max_delta: 2

#[output_pin coolant_pump]
#pin: PE5


#####################################################################
# 	Addl Temp Sensors
#####################################################################

[temperature_sensor coolant]
sensor_pin: PF5
sensor_type: EPCOS 100K B57560G104F

[temperature_sensor stepper_driver]
sensor_pin: PF7
sensor_type: EPCOS 100K B57560G104F


#####################################################################
# 	LED Control
#####################################################################

[output_pin lights]
pin: PD14
value:1
shutdown_value:0


########################################
# EXP1 / EXP2 (display) pins
########################################

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PE8, EXP1_2=PE7,
    EXP1_3=PE9, EXP1_4=PE10,
    EXP1_5=PE12, EXP1_6=PE13,    # Slot in the socket on this side
    EXP1_7=PE14, EXP1_8=PE15,
    EXP1_9=<GND>, EXP1_10=<5V>,

    # EXP2 header
    EXP2_1=PA6, EXP2_2=PA5,
    EXP2_3=PB1, EXP2_4=PA4,
    EXP2_5=PB2, EXP2_6=PA7,      # Slot in the socket on this side
    EXP2_7=PC15, EXP2_8=<RST>,
    EXP2_9=<GND>, EXP2_10=<5V>



```
